# Generated by Django 5.2.1 on 2025-06-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
